services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cliente-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cliente@123456
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - cliente-network
    restart: unless-stopped

networks:
  cliente-network:
    driver: bridge

volumes:
  sqlserver-data:
